# Configure main menu and social menu
[[main]]
identifier = "profile"
name = "Profile"
url = "/p/about"
[main.params]
icon = "person"
newtab = false
[[main]]
identifier = "research"
name = "Research"
url = "/p/research"
[main.params]
icon = "glasses"
newtab = false
[[main]]
identifier = "projects"
name = "Projects"
url = "/p/projects"
[main.params]
icon = "file"
newtab = false
[[main]]
identifier = "exercises"
name = "Exercises"
url = "/p/exercises"
[main.params]
icon = "terminal"
newtab = false

[[social]]
identifier = "email"
name = "E-mail"
url = "mailto:simongreenblatt@gmail.com"

[social.params]
icon = "email"

[[social]]
identifier = "resume"
name = "Resume"
url = "/p/about/resume_cyber.pdf"

[social.params]
icon = "info"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/simon-greenblatt"

[social.params]
icon = "linkedin"