# Configure main menu and social menu
[[main]]
identifier = "home"
name = "Home"
url = "/p/about"
[main.params]
icon = "home"
newtab = false
[[main]]
identifier = "research"
name = "Research"
url = "/p/research"
[main.params]
icon = "glasses"
newtab = false
[[main]]
identifier = "projects"
name = "Projects"
url = "/p/projects"
[main.params]
icon = "file"
newtab = false

[[social]]
identifier = "email"
name = "E-mail"
url = "mailto:scamposg@cs.brown.edu"

[social.params]
icon = "email"

[[social]]
identifier = "resume"
name = "Resume"
url = "/p/about/Resume_Cyber.pdf"

[social.params]
icon = "info"